# permissions for end users to view memhasheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memhashed-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: memcached-operator
    app.kubernetes.io/part-of: memcached-operator
    app.kubernetes.io/managed-by: kustomize
  name: memhashed-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memhasheds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memhasheds/status
  verbs:
  - get
