# permissions for end users to view immortaldbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: immortaldb-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: memcached-operator
    app.kubernetes.io/part-of: memcached-operator
    app.kubernetes.io/managed-by: kustomize
  name: immortaldb-viewer-role
rules:
- apiGroups:
  - db.example.com
  resources:
  - immortaldbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.example.com
  resources:
  - immortaldbs/status
  verbs:
  - get
